runtime: python311
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
  - url: /(.*)
    static_files: \1
    upload: /index.html/(.*)
    secure: always
